### ISSUE TITLE
Run file crash

### ISSUE THREAD

**Issue by Shweps7** [osztenkurden/CS-GO-Observer-Custom-HUD#57]
Well, none of the people responsible for this thing help, so maybe something that happened to him and managed to solve could help? When I open the run.bat it's just a course and I don't know what to do please please help please!

**Comment by AndreasZacchi** [comment]
I don't have any affiliation to this repo, but was wondering if you have Node.js installed?

**Comment by Zepedrofig** [comment]
Im also having the same issue. Here is a screenshot of the cmd when I open it. Any ideas? Also having an issue with the .exe, but might be related with this error.
Edit: I do have node.js installed
![Screenshot_1](https://user-images.githubusercontent.com/53415092/82506553-071b0680-9af8-11ea-820e-365315cbb9d4.png)

**Audit:**

![Screenshot_2](https://user-images.githubusercontent.com/53415092/82506781-a04a1d00-9af8-11ea-8ff7-1fdd2c21fdd7.png)
![Screenshot_3](https://user-images.githubusercontent.com/53415092/82506786-a17b4a00-9af8-11ea-9a64-0aa1d4e46854.png)

**Comment by AndreasZacchi** [comment]
![Annotation 2020-05-21 133220](https://user-images.githubusercontent.com/42937668/82555157-898edf00-9b67-11ea-8663-fd0f9ac1fb68.jpg)
Are you sure you didn't "pause" the command prompt window my clicking in it, perhaps try to press enter in there.

**Comment by Zepedrofig** [comment]
I’m sure I didn’t pause it. I just took the screenshot before it crashes and cmd closes. It stays like this for 1-2 sec and then the cmd closes by itself. Thanks for the answer!

**Comment by AndreasZacchi** [comment]
Is that on a clean install or have you modified anything?

**Comment by Zepedrofig** [comment]
I just cloned it and tried it out, nothing changed. Only the config file is different for obvious reasons

**Comment by AndreasZacchi** [comment]
What version of nodejs are you running, you can get it by typing
```
node -v
``` 
in a CMD anywhere

**Comment by Salty-Jayy** [comment]
In the config.json file and the gamestate_integration_observerspectator.cfg file change the GameStateIntegrationPort from 1337 to 1338.

That worked for me. Hope it helps you :)

glhf
@Salty_Jayy

**Comment by Zepedrofig** [comment]
Im running 14.3.0 but yeah, changing the port worked! Thanks!

**Comment by Zepedrofig** [comment]
Im running v14.3.0 and changing the port worked, but now the .exe file is unavailable to download. Anyone knows why?

**Comment by AndreasZacchi** [comment]
Link is down check #58 for 64 bit link.

**Comment by Zepedrofig** [comment]
I feel like Im annoying the heck out of you, but since I keep having issues, I might as well keep doing it...

So these are my config files and cfg files:
![Screenshot_1](https://user-images.githubusercontent.com/53415092/82733144-e0ccb500-9d09-11ea-9d5c-5b97849c317c.png)
![Screenshot_2](https://user-images.githubusercontent.com/53415092/82733146-e1fde200-9d09-11ea-88a4-b36217122360.png)
![Screenshot_3](https://user-images.githubusercontent.com/53415092/82733147-e32f0f00-9d09-11ea-99e6-3ece6b879f03.png)
 And when I open the HUD this shows up. 
![Screenshot_4](https://user-images.githubusercontent.com/53415092/82733180-11145380-9d0a-11ea-86f8-0d678ceaf0f4.png)

You think it might be something related with the firewall? I have kaspersky but I've allowed the app to communicate, but there might be something else that Im missing. As always, thanks a lot!

**Comment by AndreasZacchi** [comment]
No worries, would you mind trying the same in another browser? (Edge, Firefox etc.)

**Comment by Zepedrofig** [comment]
I did try to open the hud on a browser but wasn’t able to either. I then launched the chrome plugin inside the hud launcher and it did show a localhost too which I could connect to.

**Comment by AndreasZacchi** [comment]
Then it has to be something on the PC, most likely kaspersky as you stated, are you sure kaspersky and/or the local firewall has an ALLOW rule for the port?
